# -*- coding: utf-8 -*-
"""Muhammad R Faathir Habibie_Data Scrap_055.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F092tUJ0rp42RculuxOSFQog0H-_RDmC
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

books = []
for i in range(1,5):
    url = f"https://books.toscrape.com/catalogue/page-{i}.html"
    response = requests.get(url)
    response = response.content
    soup = BeautifulSoup(response, "html.parser")
    ol = soup.find("ol")
    articles = ol.find_all("article", class_="product_pod")


    for article in articles:
        image = article.find("img")
        title = image.attrs["alt"]
        star = article.find("p")
        star = star["class"][1]
        price = article.find("p", class_="price_color").text
        price = float(price[1:])
        books.append([title, price, star])

df = pd.DataFrame(books, columns=["Title", "Price", "Star Rating"])

df

df.to_csv("books.csv")